// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_REUSEMODEL_FASTBOTX_H_
#define FLATBUFFERS_GENERATED_REUSEMODEL_FASTBOTX_H_

#include "flatbuffers/flatbuffers.h"

namespace fastbotx {

struct ActivityTimes;
struct ActivityTimesBuilder;

struct ActionCounts;
struct ActionCountsBuilder;

struct PathTemplate;
struct PathTemplateBuilder;

struct PreconditionPage;
struct PreconditionPageBuilder;

struct ReuseEntry;
struct ReuseEntryBuilder;

struct ReuseModel;
struct ReuseModelBuilder;

struct ActivityTimes FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ActivityTimesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACTIVITY = 4,
    VT_TIMES = 6
  };
  const flatbuffers::String *activity() const {
    return GetPointer<const flatbuffers::String *>(VT_ACTIVITY);
  }
  int32_t times() const {
    return GetField<int32_t>(VT_TIMES, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ACTIVITY) &&
           verifier.VerifyString(activity()) &&
           VerifyField<int32_t>(verifier, VT_TIMES) &&
           verifier.EndTable();
  }
};

struct ActivityTimesBuilder {
  typedef ActivityTimes Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_activity(flatbuffers::Offset<flatbuffers::String> activity) {
    fbb_.AddOffset(ActivityTimes::VT_ACTIVITY, activity);
  }
  void add_times(int32_t times) {
    fbb_.AddElement<int32_t>(ActivityTimes::VT_TIMES, times, 0);
  }
  explicit ActivityTimesBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ActivityTimes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ActivityTimes>(end);
    return o;
  }
};

inline flatbuffers::Offset<ActivityTimes> CreateActivityTimes(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> activity = 0,
    int32_t times = 0) {
  ActivityTimesBuilder builder_(_fbb);
  builder_.add_times(times);
  builder_.add_activity(activity);
  return builder_.Finish();
}

inline flatbuffers::Offset<ActivityTimes> CreateActivityTimesDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *activity = nullptr,
    int32_t times = 0) {
  auto activity__ = activity ? _fbb.CreateString(activity) : 0;
  return fastbotx::CreateActivityTimes(
      _fbb,
      activity__,
      times);
}

struct ActionCounts FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ActionCountsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACTION = 4,
    VT_TIMES = 6
  };
  uint64_t action() const {
    return GetField<uint64_t>(VT_ACTION, 0);
  }
  int32_t times() const {
    return GetField<int32_t>(VT_TIMES, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ACTION) &&
           VerifyField<int32_t>(verifier, VT_TIMES) &&
           verifier.EndTable();
  }
};

struct ActionCountsBuilder {
  typedef ActionCounts Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_action(uint64_t action) {
    fbb_.AddElement<uint64_t>(ActionCounts::VT_ACTION, action, 0);
  }
  void add_times(int32_t times) {
    fbb_.AddElement<int32_t>(ActionCounts::VT_TIMES, times, 0);
  }
  explicit ActionCountsBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ActionCounts> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ActionCounts>(end);
    return o;
  }
};

inline flatbuffers::Offset<ActionCounts> CreateActionCounts(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t action = 0,
    int32_t times = 0) {
  ActionCountsBuilder builder_(_fbb);
  builder_.add_action(action);
  builder_.add_times(times);
  return builder_.Finish();
}

struct PathTemplate FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PathTemplateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQUENCE = 4,
    VT_RELIABILITY = 6
  };
  const flatbuffers::Vector<uint64_t> *sequence() const {
    return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_SEQUENCE);
  }
  const flatbuffers::Vector<double> *reliability() const {
    return GetPointer<const flatbuffers::Vector<double> *>(VT_RELIABILITY);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SEQUENCE) &&
           verifier.VerifyVector(sequence()) &&
           VerifyOffset(verifier, VT_RELIABILITY) &&
           verifier.VerifyVector(reliability()) &&
           verifier.EndTable();
  }
};

struct PathTemplateBuilder {
  typedef PathTemplate Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_sequence(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> sequence) {
    fbb_.AddOffset(PathTemplate::VT_SEQUENCE, sequence);
  }
  void add_reliability(flatbuffers::Offset<flatbuffers::Vector<double>> reliability) {
    fbb_.AddOffset(PathTemplate::VT_RELIABILITY, reliability);
  }
  explicit PathTemplateBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<PathTemplate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PathTemplate>(end);
    return o;
  }
};

inline flatbuffers::Offset<PathTemplate> CreatePathTemplate(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> sequence = 0,
    flatbuffers::Offset<flatbuffers::Vector<double>> reliability = 0) {
  PathTemplateBuilder builder_(_fbb);
  builder_.add_reliability(reliability);
  builder_.add_sequence(sequence);
  return builder_.Finish();
}

inline flatbuffers::Offset<PathTemplate> CreatePathTemplateDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint64_t> *sequence = nullptr,
    const std::vector<double> *reliability = nullptr) {
  auto sequence__ = sequence ? _fbb.CreateVector<uint64_t>(*sequence) : 0;
  auto reliability__ = reliability ? _fbb.CreateVector<double>(*reliability) : 0;
  return fastbotx::CreatePathTemplate(
      _fbb,
      sequence__,
      reliability__);
}

struct PreconditionPage FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PreconditionPageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HASHCODE = 4,
    VT_SCORE = 6,
    VT_ACTION_COUNTS = 8,
    VT_TEMPLATES = 10
  };
  uint64_t hashcode() const {
    return GetField<uint64_t>(VT_HASHCODE, 0);
  }
  double score() const {
    return GetField<double>(VT_SCORE, 0.0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<fastbotx::ActionCounts>> *action_counts() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<fastbotx::ActionCounts>> *>(VT_ACTION_COUNTS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<fastbotx::PathTemplate>> *templates() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<fastbotx::PathTemplate>> *>(VT_TEMPLATES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_HASHCODE) &&
           VerifyField<double>(verifier, VT_SCORE) &&
           VerifyOffset(verifier, VT_ACTION_COUNTS) &&
           verifier.VerifyVector(action_counts()) &&
           verifier.VerifyVectorOfTables(action_counts()) &&
           VerifyOffset(verifier, VT_TEMPLATES) &&
           verifier.VerifyVector(templates()) &&
           verifier.VerifyVectorOfTables(templates()) &&
           verifier.EndTable();
  }
};

struct PreconditionPageBuilder {
  typedef PreconditionPage Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_hashcode(uint64_t hashcode) {
    fbb_.AddElement<uint64_t>(PreconditionPage::VT_HASHCODE, hashcode, 0);
  }
  void add_score(double score) {
    fbb_.AddElement<double>(PreconditionPage::VT_SCORE, score, 0.0);
  }
  void add_action_counts(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::ActionCounts>>> action_counts) {
    fbb_.AddOffset(PreconditionPage::VT_ACTION_COUNTS, action_counts);
  }
  void add_templates(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::PathTemplate>>> templates) {
    fbb_.AddOffset(PreconditionPage::VT_TEMPLATES, templates);
  }
  explicit PreconditionPageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<PreconditionPage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PreconditionPage>(end);
    return o;
  }
};

inline flatbuffers::Offset<PreconditionPage> CreatePreconditionPage(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t hashcode = 0,
    double score = 0.0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::ActionCounts>>> action_counts = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::PathTemplate>>> templates = 0) {
  PreconditionPageBuilder builder_(_fbb);
  builder_.add_score(score);
  builder_.add_hashcode(hashcode);
  builder_.add_templates(templates);
  builder_.add_action_counts(action_counts);
  return builder_.Finish();
}

inline flatbuffers::Offset<PreconditionPage> CreatePreconditionPageDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t hashcode = 0,
    double score = 0.0,
    const std::vector<flatbuffers::Offset<fastbotx::ActionCounts>> *action_counts = nullptr,
    const std::vector<flatbuffers::Offset<fastbotx::PathTemplate>> *templates = nullptr) {
  auto action_counts__ = action_counts ? _fbb.CreateVector<flatbuffers::Offset<fastbotx::ActionCounts>>(*action_counts) : 0;
  auto templates__ = templates ? _fbb.CreateVector<flatbuffers::Offset<fastbotx::PathTemplate>>(*templates) : 0;
  return fastbotx::CreatePreconditionPage(
      _fbb,
      hashcode,
      score,
      action_counts__,
      templates__);
}

struct ReuseEntry FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ReuseEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACTION = 4,
    VT_TARGETS = 6
  };
  uint64_t action() const {
    return GetField<uint64_t>(VT_ACTION, 0);
  }
  bool KeyCompareLessThan(const ReuseEntry *o) const {
    return action() < o->action();
  }
  int KeyCompareWithValue(uint64_t val) const {
    return static_cast<int>(action() > val) - static_cast<int>(action() < val);
  }
  const flatbuffers::Vector<flatbuffers::Offset<fastbotx::ActivityTimes>> *targets() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<fastbotx::ActivityTimes>> *>(VT_TARGETS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ACTION) &&
           VerifyOffset(verifier, VT_TARGETS) &&
           verifier.VerifyVector(targets()) &&
           verifier.VerifyVectorOfTables(targets()) &&
           verifier.EndTable();
  }
};

struct ReuseEntryBuilder {
  typedef ReuseEntry Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_action(uint64_t action) {
    fbb_.AddElement<uint64_t>(ReuseEntry::VT_ACTION, action, 0);
  }
  void add_targets(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::ActivityTimes>>> targets) {
    fbb_.AddOffset(ReuseEntry::VT_TARGETS, targets);
  }
  explicit ReuseEntryBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ReuseEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ReuseEntry>(end);
    return o;
  }
};

inline flatbuffers::Offset<ReuseEntry> CreateReuseEntry(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t action = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::ActivityTimes>>> targets = 0) {
  ReuseEntryBuilder builder_(_fbb);
  builder_.add_action(action);
  builder_.add_targets(targets);
  return builder_.Finish();
}

inline flatbuffers::Offset<ReuseEntry> CreateReuseEntryDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t action = 0,
    const std::vector<flatbuffers::Offset<fastbotx::ActivityTimes>> *targets = nullptr) {
  auto targets__ = targets ? _fbb.CreateVector<flatbuffers::Offset<fastbotx::ActivityTimes>>(*targets) : 0;
  return fastbotx::CreateReuseEntry(
      _fbb,
      action,
      targets__);
}

struct ReuseModel FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ReuseModelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MODEL = 4,
    VT_PRECONDITION_PAGES = 6
  };
  const flatbuffers::Vector<flatbuffers::Offset<fastbotx::ReuseEntry>> *model() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<fastbotx::ReuseEntry>> *>(VT_MODEL);
  }
  const flatbuffers::Vector<flatbuffers::Offset<fastbotx::PreconditionPage>> *precondition_pages() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<fastbotx::PreconditionPage>> *>(VT_PRECONDITION_PAGES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MODEL) &&
           verifier.VerifyVector(model()) &&
           verifier.VerifyVectorOfTables(model()) &&
           VerifyOffset(verifier, VT_PRECONDITION_PAGES) &&
           verifier.VerifyVector(precondition_pages()) &&
           verifier.VerifyVectorOfTables(precondition_pages()) &&
           verifier.EndTable();
  }
};

struct ReuseModelBuilder {
  typedef ReuseModel Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_model(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::ReuseEntry>>> model) {
    fbb_.AddOffset(ReuseModel::VT_MODEL, model);
  }
  void add_precondition_pages(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::PreconditionPage>>> precondition_pages) {
    fbb_.AddOffset(ReuseModel::VT_PRECONDITION_PAGES, precondition_pages);
  }
  explicit ReuseModelBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ReuseModel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ReuseModel>(end);
    return o;
  }
};

inline flatbuffers::Offset<ReuseModel> CreateReuseModel(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::ReuseEntry>>> model = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::PreconditionPage>>> precondition_pages = 0) {
  ReuseModelBuilder builder_(_fbb);
  builder_.add_precondition_pages(precondition_pages);
  builder_.add_model(model);
  return builder_.Finish();
}

inline flatbuffers::Offset<ReuseModel> CreateReuseModelDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    std::vector<flatbuffers::Offset<fastbotx::ReuseEntry>> *model = nullptr,
    const std::vector<flatbuffers::Offset<fastbotx::PreconditionPage>> *precondition_pages = nullptr) {
  auto model__ = model ? _fbb.CreateVectorOfSortedTables<fastbotx::ReuseEntry>(model) : 0;
  auto precondition_pages__ = precondition_pages ? _fbb.CreateVector<flatbuffers::Offset<fastbotx::PreconditionPage>>(*precondition_pages) : 0;
  return fastbotx::CreateReuseModel(
      _fbb,
      model__,
      precondition_pages__);
}

inline const fastbotx::ReuseModel *GetReuseModel(const void *buf) {
  return flatbuffers::GetRoot<fastbotx::ReuseModel>(buf);
}

inline const fastbotx::ReuseModel *GetSizePrefixedReuseModel(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<fastbotx::ReuseModel>(buf);
}

inline bool VerifyReuseModelBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fastbotx::ReuseModel>(nullptr);
}

inline bool VerifySizePrefixedReuseModelBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fastbotx::ReuseModel>(nullptr);
}

inline void FinishReuseModelBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fastbotx::ReuseModel> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedReuseModelBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fastbotx::ReuseModel> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fastbotx

#endif  // FLATBUFFERS_GENERATED_REUSEMODEL_FASTBOTX_H_
